\immediate\write18{xelatex neo2}
\immediate\write18{xelatex neo3}
\immediate\write18{xelatex neo4}
\immediate\write18{xelatex neo5}
\immediate\write18{xelatex neo6}

\immediate\write18{xelatex ebene12}
\immediate\write18{xelatex ebene3}
\immediate\write18{xelatex ebene4}
\immediate\write18{xelatex ebene5}
\immediate\write18{xelatex ebene6}

\immediate\write18{pdflatex neo+xelatex}
\immediate\write18{bibtex neo+xelatex}
\immediate\write18{pdflatex neo+xelatex}
\immediate\write18{pdflatex neo+xelatex}
\stop